
apiVersion: v1
kind: ConfigMap
metadata:
  name: l2-env
data:
  .env: |
    # L1 info
    ETH_RPC_URL=
    L1_ChainID=
    L1_BlockTime=
    L1_RPC_KIND=basic

    # L2 config
    L2_ChainID=
    L2_BlockTime=

    # Accounts KEY without suffix
    ADMIN=
    PRIVATE_KEY=
    SEQUENCER=
    SEQUENCER_KEY=
    BATCHER=
    BATCHER_KEY=
