apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: l2-verifier-explorer
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  selector:
    matchLabels:
      app: l2-verifier-explorer
  serviceName: ''
  template:
    metadata:
      labels:
        app: l2-verifier-explorer
    spec:
      containers:
      - args:
        - -c
        - max_connections=200
        env:
        - name: POSTGRES_PASSWORD
          value: '123456'
        image: docker.io/postgres:alpine3.18
        imagePullPolicy: IfNotPresent
        name: eth-postgres
        ports:
        - containerPort: 5432
          name: postgres
          protocol: TCP
        resources:
          limits:
            cpu: 4000m
            memory: 8196Mi
          requests:
            cpu: 1000m
            memory: 2048Mi
        volumeMounts:
        - mountPath: /var/lib/pgsql
          name: datadir-verifier-explorer
      - command:
        - ./smart-contract-verifier-server
        - -c
        - /opt/base.toml
        image: docker.io/citacloud/smart-contract-verifier:latest
        imagePullPolicy: IfNotPresent
        name: eth-svc
        ports:
        - containerPort: 8050
          name: svc
          protocol: TCP
        resources:
          limits:
            cpu: 2000m
            memory: 4098Mi
          requests:
            cpu: 1000m
            memory: 2048Mi
        volumeMounts:
        - mountPath: /opt
          name: l2-explorer-scv
      - command:
        - /bin/sh
        - -c
        - bin/blockscout eval "Elixir.Explorer.ReleaseTasks.create_and_migrate()"
          && bin/blockscout start
        env:
        - name: ETHEREUM_JSONRPC_VARIANT
          value: geth
        - name: ETHEREUM_JSONRPC_HTTP_URL
          value: http://l2-verifier-rpc:8545
        - name: DATABASE_URL
          value: postgresql://postgres:123456@localhost:5432/blockscout?ssl=false
        - name: ECTO_USE_SSL
          value: 'false'
        - name: SECRET_KEY_BASE
          value: 56NtB48ear7+wMSf0IQuWDAAazhpb31qyc7GiyspBP2vh7t5zlCsF5QDv76chXeN
        - name: PORT
          value: '4000'
        - name: INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER
          value: 'true'
        - name: MICROSERVICE_SC_VERIFIER_ENABLED
          value: 'true'
        - name: MICROSERVICE_SC_VERIFIER_URL
          value: http://localhost:8050/
        - name: COIN_NAME
          value: CTT
        image: docker.io/blockscout/blockscout:frontend-main
        imagePullPolicy: IfNotPresent
        name: eth-blockscout
        ports:
        - containerPort: 4000
          name: blockscout
          protocol: TCP
        resources:
          limits:
            cpu: 4000m
            memory: 8196Mi
          requests:
            cpu: 2000m
            memory: 4098Mi
      volumes:
      - configMap:
          name: l2-explorer-scv
        name: l2-explorer-scv
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: datadir-verifier-explorer
    spec:
      accessModes:
      - ReadWriteMany
      resources:
        requests:
          storage: 50Gi
      storageClassName: ''
      volumeMode: Filesystem
