apiVersion: v1
kind: Service
metadata:
  name: l2-verifier-explorer
spec:
  ports:
  - name: rpc
    port: 4000
    protocol: TCP
    targetPort: 4000
  selector:
    app: l2-verifier-explorer
  type: LoadBalancer
