apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: l2-verifier
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  selector:
    matchLabels:
      app: l2-verifier
  serviceName: ''
  template:
    metadata:
      labels:
        app: l2-verifier
    spec:
      containers:
      - args:
        - 'geth --datadir /datadir --http --http.corsdomain="*" --http.vhosts="*"
          --http.addr=0.0.0.0 \

          --http.api=web3,debug,eth,txpool,net,engine --ws --ws.addr=0.0.0.0 --ws.port=8546
          --ws.origins="*" \

          --ws.api=debug,eth,txpool,net,engine --syncmode=full --gcmode=archive --authrpc.jwtsecret=/config/jwt.txt
          \

          --networkid=$(cat /config/L2_ChainID) --authrpc.vhosts="*" --authrpc.addr=0.0.0.0
          --authrpc.port=8551 \

          --bootnodes=enode://$(cat /config/OP_GETH_P2P)@l2-sequencer-p2p:30303 \

          --txpool.pricelimit=0

          '
        command:
        - /bin/sh
        - -c
        image: docker.io/jayanring/op-geth
        imagePullPolicy: IfNotPresent
        name: op-geth
        ports:
        - containerPort: 8545
          name: op-geth-rpc
          protocol: TCP
        - containerPort: 8551
          name: authrpc
          protocol: TCP
        resources:
          limits:
            cpu: 8000m
            memory: 16392Mi
          requests:
            cpu: 1000m
            memory: 2048Mi
        volumeMounts:
        - mountPath: /config
          name: l2-config
        - mountPath: /datadir
          name: datadir-verifier
      - args:
        - 'op-node \

          --l1=$(cat /config/ETH_RPC_URL)  \

          --l1.rpckind=basic \

          --l2=http://localhost:8551/ \

          --l2.jwt-secret=/config/jwt.txt \

          --rollup.config=/config/rollup.json \

          --rpc.addr=0.0.0.0 \

          --rpc.port=8547 \

          --p2p.static /dns4/l2-sequencer-p2p/tcp/9222/p2p/$(cat /config/OP_NODE_P2P)
          \

          --l1.trustrpc

          '
        command:
        - /bin/sh
        - -c
        image: docker.io/jayanring/op-node
        imagePullPolicy: IfNotPresent
        name: op-node
        ports:
        - containerPort: 8547
          name: op-node-rpc
          protocol: TCP
        resources:
          limits:
            cpu: 8000m
            memory: 16392Mi
          requests:
            cpu: 1000m
            memory: 2048Mi
        volumeMounts:
        - mountPath: /config
          name: l2-config
      initContainers:
      - args:
        - "echo \"datadir: $(ls /datadir)\";\nif [ ! \"$(ls -A /datadir)\" ]; then\n\
          \  echo \"init geth\" && geth init --datadir=/datadir /config/genesis.json\n\
          fi\n"
        command:
        - /bin/sh
        - -c
        image: docker.io/jayanring/op-geth
        imagePullPolicy: IfNotPresent
        name: init-container
        volumeMounts:
        - mountPath: /config
          name: l2-config
        - mountPath: /datadir
          name: datadir-verifier
      volumes:
      - name: l2-config
        persistentVolumeClaim:
          claimName: l2-config-pvc
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: datadir-verifier
    spec:
      accessModes:
      - ReadWriteMany
      resources:
        requests:
          storage: 10Gi
      storageClassName: ''
      volumeMode: Filesystem
