apiVersion: v1
kind: Service
metadata:
  name: l2-verifier-rpc
spec:
  ports:
  - name: rpc
    port: 8545
    protocol: TCP
    targetPort: 8545
  selector:
    app: l2-verifier
  type: LoadBalancer
