apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: l2-config-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  storageClassName: nas-client-provisioner
  volumeMode: Filesystem