apiVersion: v1
kind: Pod
metadata:
  name: l2-test
spec:
  volumes:
    - persistentVolumeClaim:
        claimName: l2-config-pvc
      name: l2-config
  containers:
  - name: busybox
    image: busybox
    command:
      - sleep
      - "36000"
    volumeMounts:
    - name: l2-config
      mountPath: /config
    resources:
      limits:
        cpu: 8000m
        memory: 16392Mi
      requests:
        cpu: 1000m
        memory: 2048Mi

